using System.Collections.Generic;
using System.Linq;
using EDTree;
using EDTree2.form.option;

namespace EDTree2
{
    public class EDTree
    {

        public Input Input { get; }
        public EdtreeOption Option { get; private set; }

        public List<double> X => Input.Data[0];
        public string[] Header => Input.Header;
        public string LabelX => Input.LabelX;
        public string LabelY => Input.LabelY;

        /// <summary>
        /// Geometrically upper line.
        /// </summary>
        public FittingLine UpperLine { get; private set; }
        
        /// <summary>
        /// Geometrically middle line.
        /// </summary>
        public FittingLine BaseLine { get; private set; }
        
        /// <summary>
        /// Geometrically lower line.
        /// </summary>
        public FittingLine LowerLine { get; private set; }
        
        // Rects.
        private FittingRect _rect;
        private FittingEllipse _ellipse;

        public EDTree(Input input)
        {
            Input = input;
        }

        /// <summary>
        /// Set Edtree option that contains user's input.
        /// </summary>
        public EDTree SetOption(EdtreeOption option)
        {
            Option = option;
            return this;
        }
        
        /// <summary>
        /// Calculate and create line equations, rectangles, and ellipses with the given option.
        /// </summary>
        public EDTree Calculate()
        {
            var (upper, baseline, lower) = DivideInputData();

            UpperLine = new FittingLine(X, upper, Option.Order).Fit();
            BaseLine = new FittingLine(X, baseline, Option.Order).Fit();
            LowerLine = new FittingLine(X, lower, Option.Order).Fit();

            _rect = new FittingRect(Option.ZstepMin, Option.ZstepMax, UpperLine, LowerLine).Calculate();
            _ellipse = new FittingEllipse(Option.EllipseMinX, Option.EllipseMaxX, UpperLine, LowerLine).Calculate();

            return this;
        }

        /// <summary>
        /// Returns x values that generated by iteration.
        /// </summary>
        /// <param name="step">The value added in the iteration.</param>
        public List<double> GetXPoints(double step = 0.001)
        {
            double start = X.Min();
            double end = X.Max();

            List<double> xPoints = new List<double>();
            for (double i = start; i <= end; i += step)
            {
                xPoints.Add(i);
            }

            return xPoints;
        }

        /// <summary>
        /// Return Rectangle with the given style.
        /// </summary>
        public RectPoint GetRectangles(RectStyle style)
        {
            switch (style)
            {
                case RectStyle.None:
                    return null;
                case RectStyle.Left:
                    return _rect.GetRect(FittingType.Left);
                case RectStyle.Right:
                    return _rect.GetRect(FittingType.Right);
                case RectStyle.Avg:
                    return _rect.GetRect(FittingType.Average);
                case RectStyle.Max:
                    return _rect.GetRect(FittingType.Max);
            }

            return null;
        }

        /// <summary>
        /// Return Ellipse with the given style.
        /// </summary>
        public EllipsePoint GetEllipse(EllipseStyle style)
        {
            switch (style)
            {
                case EllipseStyle.Max:
                    return _ellipse.Ellipse;
            }

            return null;
        }
        
        /// <summary>
        /// Paring Input to upper, base, lower lines.
        /// It assumes that the three lines are placed in order.
        /// </summary>
        private (List<double> upper, List<double> baseline, List<double> lower) DivideInputData()
        {
            var lines = new[] {Input.Data[1], Input.Data[2], Input.Data[3]};
            var orderedList = lines.OrderBy(v => v[0]).ToList();
            return (orderedList[0], orderedList[1], orderedList[2]);
        }
    }
}