using System.Collections.Generic;
using System.Linq;
using MathNet.Numerics;

namespace EDTree
{
    /// <summary>
    /// Find the best fitting line based on Least-Square algorithm.
    /// </summary>
    public class FittingLine
    {
        /// <summary>
        /// Given x values to find the best fitting line.
        /// </summary>
        public List<double> X { get; set; }
        
        /// <summary>
        /// Given y values to find the best fitting line.
        /// </summary>
        public List<double> Y { get; set; }
        
        /// <summary>
        /// Maximum rank fot Least-square polynomial equation.
        /// </summary>
        public int Order { get; set; }
        
        /// <summary>
        /// The value used for iteration in points. 
        /// </summary>
        public double Step { get; set; }
        
        /// <summary>
        /// The best fitting line.
        /// </summary>
        public Polynomial F { get; private set; }
        
        /// <summary>
        /// Coefficients for the best fitting line.
        /// </summary>
        public double[] Coefficients => F.Coefficients;
        
        /// <summary>
        /// The square of the sample correlation coefficient. 
        /// </summary>
        public double RSquare { get; private set; }
        
        /// <summary>
        /// The x values generated by iteration with Step.
        /// </summary>
        private List<double> PointX { get; set; }
        
        /// <summary>
        /// The y values generated by iteration with Step.
        /// </summary>
        private List<double> PointY { get; set; }
        
        public FittingLine(List<double> x, List<double> y, int order=2, double step = 0.001)
        {
            X = x;
            Y = y;
            Order = order;
            Step = step;

            PointX = new List<double>();
            PointY = new List<double>();
        }

        /// <summary>
        /// Least-Square fitting the points (x, y), returning the best fitting line.
        /// </summary>
        public FittingLine Fit()
        {
            // generate polynomial equation.
            F = new Polynomial(MathNet.Numerics.Fit.Polynomial(X.ToArray(), Y.ToArray(), Order));
            RSquare = GoodnessOfFit.RSquared(X.Select(x => F.Evaluate(x)), Y);

            // pre-calculate points on the equation.
            PointX.Clear();
            PointY.Clear();
            var min = X.Min();
            var max = X.Max();
            for (var x = min; x <= max; x+=Step)
            {
                PointX.Add(x);
                PointY.Add(F.Evaluate(x));
            }

            return this;
        }

        /// <summary>
        /// Evaluate F(x) for given x
        /// </summary>
        public double Evaluate(double x)
        {
            return F.Evaluate(x);
        }

        /// <summary>
        /// Find maximum value of the equation.
        /// </summary>
        public PointD MaxY()
        {
            var ymax = PointY.Max();
            var x = PointX[PointY.IndexOf(ymax)];
            return new PointD(x, ymax);
        }

        /// <summary>
        /// Solve the equation to find x with given y.
        /// </summary>
        /// <param name="y">F(x) value to find x in the equation.</param>
        /// <param name="maximumAbsoluteError">The accuracy required for comparing double values.</param>
        /// <returns>List of x values that can be empty.</returns>
        public List<double> FindXByY(double y, double maximumAbsoluteError = 0.0001)
        {
            var res = new List<double>();

            for (var i = 0; i < PointX.Count; i++)
            {
                
                if (PointY[i].AlmostEqual(y, maximumAbsoluteError))
                    res.Add(PointX[i]);
            }

            return res;
        }
    }
}